"""
    EOD Historical Data API

    EOD Historical Data API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.asset_fundamentals_section_general import AssetFundamentalsSectionGeneral


class TestAssetFundamentalsSectionGeneral(unittest.TestCase):
    """AssetFundamentalsSectionGeneral unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetFundamentalsSectionGeneral(self):
        """Test AssetFundamentalsSectionGeneral"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AssetFundamentalsSectionGeneral()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
