"""
    EOD Historical Data API

    EOD Historical Data API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.exchanges_api import ExchangesApi  # noqa: E501


class TestExchangesApi(unittest.TestCase):
    """ExchangesApi unit test stubs"""

    def setUp(self):
        self.api = ExchangesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_echanges(self):
        """Test case for list_echanges

        Search symbols  # noqa: E501
        """
        pass

    def test_list_symbols(self):
        """Test case for list_symbols

        Search symbols  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
