"""
    EOD Historical Data API

    EOD Historical Data API  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sam@sddproductions.com
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.symbol_search import SymbolSearch


class TestSymbolSearch(unittest.TestCase):
    """SymbolSearch unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSymbolSearch(self):
        """Test SymbolSearch"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SymbolSearch()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
